# !/bin/bash
#Variables
#App GW
export TF_VAR_JENKINS_APP_GATEWAY_FRONTEND_TLS_CERT_PFXA="${JENKINS_APP_GATEWAY_FRONTEND_TLS_CERT_PFXA}"
export TF_VAR_JENKINS_APP_GATEWAY_FRONTEND_TLS_CERT_PASSA="${JENKINS_APP_GATEWAY_FRONTEND_TLS_CERT_PASSA}"

#Functions
#App GW Cert Function
appgw_cert() {
echo "$JENKINS_APP_GATEWAY_FRONTEND_TLS_CERTA" | base64 -di > $TF_VAR_JENKINS_APP_GATEWAY_FRONTEND_TLS_CERT_PFXA
}
